<?php

$config['sysconfig'] = array(
    'App' => array(
        'status' => array(
            -1 => __('status_rejected'),
            0 => __('status_hidden'),
            1 => __('status_wait_review'),
            2 => __('status_approved'),
        ),
        'constants' => array(
            'STATUS_APPROVED' => 2,
            'STATUS_ACTIVE' => 1,
            'STATUS_WAIT_REVIEW' => 1,
            'LANG_CODE' => 'vi',
            'CURRENCY_CODE' => 'VND',
            'DISTANCE' => 2, // 2 km
            'STATUS_HIDDEN' => 0,
            'STATUS_REGISTER' => 0,
        ),
        'GeoJSON_type' => 'Point',
        'token' => array(
            'ttl' => array(
                'short' => '+1 month',
                'long' => '+2 months',
            ),
            'secret' => 'trungpolit',
            'iss' => 'hallovn',
            'aud' => 'hallovn',
        ),
        'authorize' => array(
            'username_fields' => array(// các trường fields dùng để đăng nhập tương đương username
                'username',
                'email',
                'mobile',
            ),
        ),
        'VMS' => array(
            'LSB' => array(
                'api_key' => '123456',
                'api_url' => 'http://10.151.22.94:5000/',
                'cp_id' => 10014,
                'service_id' => 1000211,
                'timeout' => 3,
                'connect_timeout' => 3,
            ),
        ),
        'name' => 'GameQuiz',
    ),
    'SmsSender' => array(
        'api_key' => '5dc2eb7f9d609aeedb6f302560f48cc820649c1a',
        'service_url' => 'http://10.54.3.181:9091/cgi-bin/sendsms',
        'password_length' => 4,
        'status' => 1,
        'reset_password_content' => 'Mat khau de su dung dich vu HaloVietNam la %s. Ban su dung mat khau nay cung so dien thoai %s de dang nhap va su dung dich vu.',
        'reset_password_action' => 'RESET_PASSWORD',
        'sms_hello' => 'Xin chao ',
        'sms_conten_2' => '. Ban dang co ',
    ),
    'SERVICE_CODE' => array(
        'GAME_QUIZ' => 'GAME_QUIZ'
    ),
    'Players' => array(
        'STATUS' => [
            'CANCEL' => 0,
            'REGISTER' => 1,
            'NOT_CHARGE' => 2,
        ],
        'ACTION' => [
            'DANG_KY' => 'DANG_KY',
            'HUY' => 'HUY',
            'MUA' => 'MUA',
            'TRA_LOI' => 'TRA_LOI',
            'CHOI' => 'CHOI',
            'BO_QUA' => 'BO_QUA', //TIẾP
            'CHUYEN' => 'CHUYEN',
            'HUONG_DAN' => 'HUONG_DAN',
            'XEM_KET_QUA' => 'XEM_KET_QUA',
            'GIA_HAN' => 'GIA_HAN',
            'KHAC' => 'KHAC',
        ],
        'TTL_ANSWER' => '+3 minutes',
    ),
    'SEQ_TBL_KEY' => array(
        'seq_tbl_charge' => 'seq_tbl_charge',
    ),
    'ChargingVMS' => array(
        'key' => '9ABxlwWpn6mGzdlU',
        'sp_id' => '035',
        'MUA_price' => 20,
        'G1_price' => 20,
        'G7_price' => 90,
        'RESULT_CHARGE_OK' => "CPS-0000",
        'RESULT_CHARGE_NOK' => "CPS-1001",
        'url_charge' => "http://dangky.mobifone.com.vn/wap/html/sp/confirm.jsp",
        'url_return' => "http://124.158.5.134:8083/Players/registresult",
        'diameter' => 'http://10.54.3.181:8002/diameter/charge?msisdn=%s&amount=%s',
//        'url_charge' => "http://localhost/2vietnam_wap/Tests/fakeMobifoneGateWay?trans_id=%s&msisdn=%s&status=%s",
        'diameter_test' => 'http://localhost/2vietnam_wap/Tests/fakeMobifoneCharge?code=%s',
    ),
    'Visitors' => array(
        'time_lock_reset_password' => 5,
        'default_notification_group_id' => '558ab9dc189dc030646cb6f1',
        'wrong_password_title' => 'SAI MẬT KHẨU',
        'wrong_password_content' => 'Nhập số điện thoại và chọn Nhận mật khẩu qua tin nhắn để lấy lại mật khẩu',
//        'wrong_mobile_title' => 'Số điện thoại không phải là Mobifone hoặc không đúng định dạng',
//        'wrong_mobile_content' => 'Dich vu chi danh cho thue bao Mobifone. De duoc huong dan su dung dich vu Vuot Dinh Pan Xi Phang va tham gia tranh THUONG.... DONG moi tuan, soan HD PAN gui 9144, DT ho tro 9090 (200d/phut)',
        'wrong_mobile_title' => '',
        'wrong_mobile_content' => 'Sai định dạng thuê bao Mobifone',
//        'unregister_title' => 'Số điện thoại là Mobifone nhưng chưa đăng ký dịch vụ',
//        'unregister_content' => 'Ban chua dang ky dich vu Vuot Dinh Pan Xi Phang. De dang ky soan DK<Tengoi> gui 9144 (Tengoi : G1, G7) Ban co co hoi tranh giai thuong len den... dong. Chi tiet vui long soan HD PAN gui 9144 hoac LH 9090 (200d/phut). Tran trong.',
        'unregister_title' => '',
        'unregister_content' => 'Bạn chưa đăng ký dịch vụ <strong>Vượt Đỉnh Pan Xi Phang</strong>. Để đăng ký soạn <strong>DK<Tengoi></strong> gửi <strong>9144</strong> (Tengoi : G1, G7). Bạn có cô hội tranh giải thưởng lên đến ... đồng. Chi tiết vui lòng soạn <strong>HD PAN</strong> gửi <strong>9144</strong> hoặc LH 9090 (200đ/phút). Trân trọng.',
        'not_yet_register_title' => 'BẠN CHƯA ĐĂNG KÝ DỊCH VỤ',
        'not_yet_register_content' => 'Để đăng ký soạn DK<Tengoi> gửi 9144 (Tengoi : G1, G7). Chi tiết vui lòng soạn HD PAN gửi 9144 hoặc LH 9090 (200d/phút).',
        'error_system_title' => 'Hệ thống lỗi',
        'error_system_content' => 'Hiện tại hệ thống đang gặp sự cố.',
        'empty_mobile_title' => '',
        'empty_mobile_content' => 'Hãy nhập vào số điện thoại',
        'empty_password_title' => '',
        'empty_password_content' => 'Hãy nhập vào mật khẩu',
    ),
    'Packages' => array(
        'reward_first_register' => array(
            'question_group' => 3,
            'score' => 100,
        ),
        'extra' => '2.000d',
        'day' => '2.000d',
        'week' => '9.000d',
        'buy_amount' => 20,
        'buy_question_group' => 1,
        'G1_question_group' => 3,
        'G7_question_group' => 3,
        'NOK_NO_MORE_CREDIT_AVAILABLE_TITLE' => 'THUÊ BAO KHÔNG ĐỦ SỐ DƯ',
        'NOK_NO_MORE_CREDIT_AVAILABLE_CONTENT' => 'Vui lòng nạp thêm tiền và đăng ký lại',
        'error_system_title' => 'Hệ thống lỗi',
        'error_system_content' => 'Hiện tại hệ thống đang gặp sự cố.',
        'empty_question_daily_title' => 'Bạn đã sử dụng hết 15 câu hỏi của gói %s trong ngày hôm nay',
        'empty_question_daily_content' => 'Bạn có thể <strong>CHỌN</strong> mua thêm gói <strong>%s</strong> hoặc gói <strong>MUA THÊM</strong> câu hỏi sau đó <strong>ĐỒNG Ý</strong> để xác nhận',
        'empty1_question_daily_title' => 'Bạn đã sử dụng hết 15 câu hỏi của gói %s trong ngày hôm nay',
        'empty1_question_daily_content' => 'Bạn có thể <strong>CHỌN</strong> mua thêm gói <strong>MUA THÊM</strong> câu hỏi sau đó <strong>ĐỒNG Ý</strong> để xác nhận',
        'unregister_title' => 'Bạn chưa đăng ký dịch vụ <strong>Vượt Đỉnh Pan Xi Phang</strong>',
        'unregister_content' => 'Bạn có thể <strong>CHỌN</strong> mua gói <strong>G1</strong>, <strong>G7</strong> sau đó <strong>ĐỒNG Ý</strong> để xác nhận',
        'cancel_register_title' => 'Hủy bỏ',
        'cancel_register_content' => 'Bạn chưa đăng ký dịch vụ <strong>Vượt Đỉnh Pan Xi Phang</strong> thành công',
        'usage_question' => 'Bạn đã sử dụng %s câu hỏi trong ngày hôm nay. Bạn còn %s câu hỏi. Bạn có thể chọn mua thêm gói cước bằng cách ấn vào nút “Chọn” và ấn “Đồng ý” để xác nhận',
    ),
    'Rating' => array(
        'limit' => 2,
        'status' => 1,
        'page' => 1,
        'startYear' => 2015,
        'mon_week' => array(
            '0' => 'Tuần',
            '1' => 'Tháng',
        ),
        'error_msg' => 'Không tìm thấy kết quả phù hợp',
        'replacestr' => 'XXX',
    ),
);

